version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mymeds-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployment/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - mymeds-network
    command: --default-authentication-plugin=mysql_native_password

  # MyMeds Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: mymeds-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      PORT: 4000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    networks:
      - mymeds-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MyMeds Frontend
  frontend:
    image: nginx:alpine
    container_name: mymeds-frontend
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - mymeds-network

  # WordPress (if needed)
  wordpress:
    image: wordpress:6.4-php8.2-apache
    container_name: mymeds-wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://mymedspharmacyinc.com/blog');
        define('WP_SITEURL', 'https://mymedspharmacyinc.com/blog');
    volumes:
      - wordpress_data:/var/www/html
      - ./deployment/wordpress/.htaccess:/var/www/html/.htaccess
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mymeds-network

volumes:
  mysql_data:
  wordpress_data:

networks:
  mymeds-network:
    driver: bridge




