#!/bin/bash

# Production Cache Setup Script for MyMeds Pharmacy
# This script sets up Redis, configures caching, and optimizes the application for production

set -e

echo "🚀 Setting up Production Cache for MyMeds Pharmacy..."
echo "=================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [[ $EUID -eq 0 ]]; then
        print_error "This script should not be run as root"
        exit 1
    fi
}

# Detect OS
detect_os() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if [ -f /etc/debian_version ]; then
            OS="debian"
        elif [ -f /etc/redhat-release ]; then
            OS="redhat"
        else
            OS="unknown"
        fi
    else
        print_error "Unsupported operating system: $OSTYPE"
        exit 1
    fi
    print_status "Detected OS: $OS"
}

# Install Redis
install_redis() {
    print_status "Installing Redis..."
    
    if [[ "$OS" == "debian" ]]; then
        sudo apt update
        sudo apt install -y redis-server
    elif [[ "$OS" == "redhat" ]]; then
        sudo yum install -y redis
    else
        print_error "Cannot install Redis on this OS"
        exit 1
    fi
    
    print_success "Redis installed successfully"
}

# Configure Redis
configure_redis() {
    print_status "Configuring Redis..."
    
    # Backup original config
    sudo cp /etc/redis/redis.conf /etc/redis/redis.conf.backup
    
    # Create optimized Redis configuration
    sudo tee /etc/redis/redis.conf > /dev/null <<EOF
# Redis Configuration for MyMeds Pharmacy Production
# Generated by setup-production-cache.sh

# Network
bind 127.0.0.1
port 6379
timeout 300
tcp-keepalive 60

# General
daemonize yes
supervised systemd
pidfile /var/run/redis/redis-server.pid
loglevel notice
logfile /var/log/redis/redis-server.log

# Memory Management
maxmemory 512mb
maxmemory-policy allkeys-lru
maxmemory-samples 5

# Persistence
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /var/lib/redis

# Append Only File
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Security
# requirepass your_redis_password_here

# Performance
tcp-backlog 511
databases 16
always-show-logo yes
EOF

    print_success "Redis configuration updated"
}

# Set Redis password
set_redis_password() {
    print_status "Setting up Redis password..."
    
    read -s -p "Enter Redis password (or press Enter for no password): " REDIS_PASSWORD
    echo
    
    if [[ -n "$REDIS_PASSWORD" ]]; then
        # Add password to config
        sudo sed -i "s/# requirepass your_redis_password_here/requirepass $REDIS_PASSWORD/" /etc/redis/redis.conf
        
        # Store password in environment
        echo "REDIS_PASSWORD=$REDIS_PASSWORD" >> ~/.bashrc
        
        print_success "Redis password configured"
    else
        print_warning "Redis will run without password (not recommended for production)"
    fi
}

# Start and enable Redis
start_redis() {
    print_status "Starting Redis service..."
    
    sudo systemctl start redis-server
    sudo systemctl enable redis-server
    
    # Wait for Redis to start
    sleep 3
    
    # Test Redis connection
    if redis-cli ping | grep -q "PONG"; then
        print_success "Redis is running and responding"
    else
        print_error "Redis failed to start or respond"
        exit 1
    fi
}

# Install Node.js dependencies
install_dependencies() {
    print_status "Installing Node.js dependencies..."
    
    cd backend
    npm install redis @types/redis
    
    print_success "Node.js dependencies installed"
    cd ..
}

# Configure environment variables
configure_environment() {
    print_status "Configuring environment variables..."
    
    # Create production environment file
    cat >> backend/.env.production <<EOF

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=$REDIS_PASSWORD

# Cache Configuration
CACHE_ENABLED=true
CACHE_DEFAULT_TTL=300
CACHE_PRODUCTS_TTL=1800
CACHE_POSTS_TTL=3600
CACHE_ADMIN_TTL=300
CACHE_USER_SESSION_TTL=86400

# Performance Configuration
ENABLE_CACHE_WARMING=true
CACHE_WARMING_INTERVAL=3600000
ENABLE_CACHE_METRICS=true

# CDN Configuration (if using CDN)
CDN_ENABLED=false
CDN_URL=
CDN_CACHE_TTL=14400
EOF

    print_success "Environment variables configured"
}

# Create systemd service for cache warming
create_cache_service() {
    print_status "Creating cache warming service..."
    
    sudo tee /etc/systemd/system/mymeds-cache-warming.service > /dev/null <<EOF
[Unit]
Description=MyMeds Pharmacy Cache Warming Service
After=network.target

[Service]
Type=oneshot
User=www-data
WorkingDirectory=$(pwd)/backend
ExecStart=/usr/bin/node -e "
const { CacheWarmingService } = require('./dist/services/EnhancedCacheIntegration');
CacheWarmingService.warmAllCaches().then(() => {
  console.log('Cache warming completed');
  process.exit(0);
}).catch((err) => {
  console.error('Cache warming failed:', err);
  process.exit(1);
});
"
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    # Create timer for periodic cache warming
    sudo tee /etc/systemd/system/mymeds-cache-warming.timer > /dev/null <<EOF
[Unit]
Description=MyMeds Pharmacy Cache Warming Timer
Requires=mymeds-cache-warming.service

[Timer]
OnCalendar=hourly
Persistent=true

[Install]
WantedBy=timers.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable mymeds-cache-warming.timer
    
    print_success "Cache warming service created"
}

# Create monitoring script
create_monitoring_script() {
    print_status "Creating cache monitoring script..."
    
    sudo tee /usr/local/bin/mymeds-cache-monitor.sh > /dev/null <<'EOF'
#!/bin/bash

# MyMeds Cache Monitoring Script

REDIS_PASSWORD=${REDIS_PASSWORD:-""}

# Check Redis status
check_redis() {
    if [[ -n "$REDIS_PASSWORD" ]]; then
        redis-cli -a "$REDIS_PASSWORD" ping | grep -q "PONG"
    else
        redis-cli ping | grep -q "PONG"
    fi
}

# Get cache metrics
get_cache_metrics() {
    curl -s http://localhost:4000/api/woocommerce/cache/metrics | jq '.'
}

# Main monitoring function
main() {
    echo "=== MyMeds Cache Monitoring ==="
    echo "Timestamp: $(date)"
    echo
    
    # Check Redis
    if check_redis; then
        echo "✅ Redis: Running"
    else
        echo "❌ Redis: Not responding"
    fi
    
    # Check cache metrics (if API is running)
    if curl -s http://localhost:4000/api/health > /dev/null; then
        echo "✅ API: Running"
        echo
        echo "Cache Metrics:"
        get_cache_metrics
    else
        echo "❌ API: Not responding"
    fi
    
    echo
    echo "=== End Monitoring ==="
}

main "$@"
EOF

    sudo chmod +x /usr/local/bin/mymeds-cache-monitor.sh
    
    print_success "Cache monitoring script created"
}

# Setup log rotation
setup_log_rotation() {
    print_status "Setting up log rotation..."
    
    sudo tee /etc/logrotate.d/mymeds-cache > /dev/null <<EOF
/var/log/redis/redis-server.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 redis redis
    postrotate
        systemctl reload redis-server
    endscript
}

$(pwd)/backend/logs/*.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 www-data www-data
}
EOF

    print_success "Log rotation configured"
}

# Create backup script
create_backup_script() {
    print_status "Creating cache backup script..."
    
    sudo tee /usr/local/bin/mymeds-cache-backup.sh > /dev/null <<EOF
#!/bin/bash

# MyMeds Cache Backup Script

BACKUP_DIR="/var/backups/mymeds-cache"
DATE=\$(date +%Y%m%d_%H%M%S)
REDIS_PASSWORD=\${REDIS_PASSWORD:-""}

mkdir -p \$BACKUP_DIR

# Backup Redis data
if [[ -n "\$REDIS_PASSWORD" ]]; then
    redis-cli -a "\$REDIS_PASSWORD" --rdb \$BACKUP_DIR/redis_backup_\$DATE.rdb
else
    redis-cli --rdb \$BACKUP_DIR/redis_backup_\$DATE.rdb
fi

# Clean old backups (keep 7 days)
find \$BACKUP_DIR -name "redis_backup_*.rdb" -mtime +7 -delete

echo "Cache backup completed: \$BACKUP_DIR/redis_backup_\$DATE.rdb"
EOF

    sudo chmod +x /usr/local/bin/mymeds-cache-backup.sh
    
    # Add to crontab for daily backups
    (crontab -l 2>/dev/null; echo "0 2 * * * /usr/local/bin/mymeds-cache-backup.sh") | crontab -
    
    print_success "Cache backup script created"
}

# Performance tuning
performance_tuning() {
    print_status "Applying performance tuning..."
    
    # Increase file descriptor limits
    sudo tee -a /etc/security/limits.conf > /dev/null <<EOF
* soft nofile 65536
* hard nofile 65536
EOF

    # Optimize kernel parameters
    sudo tee -a /etc/sysctl.conf > /dev/null <<EOF

# MyMeds Performance Tuning
net.core.somaxconn = 65536
net.ipv4.tcp_max_syn_backlog = 65536
vm.overcommit_memory = 1
EOF

    sudo sysctl -p
    
    print_success "Performance tuning applied"
}

# Final setup and testing
final_setup() {
    print_status "Running final setup and testing..."
    
    # Restart Redis with new configuration
    sudo systemctl restart redis-server
    
    # Test Redis connection
    sleep 3
    if redis-cli ping | grep -q "PONG"; then
        print_success "Redis restarted successfully"
    else
        print_error "Redis failed to restart"
        exit 1
    fi
    
    # Start cache warming timer
    sudo systemctl start mymeds-cache-warming.timer
    
    print_success "Cache warming timer started"
}

# Main execution
main() {
    print_status "Starting MyMeds Production Cache Setup..."
    
    check_root
    detect_os
    install_redis
    configure_redis
    set_redis_password
    start_redis
    install_dependencies
    configure_environment
    create_cache_service
    create_monitoring_script
    setup_log_rotation
    create_backup_script
    performance_tuning
    final_setup
    
    echo
    print_success "🎉 Production Cache Setup Completed!"
    echo
    echo "Next Steps:"
    echo "1. Update your application to use the new cache service"
    echo "2. Test cache functionality: /usr/local/bin/mymeds-cache-monitor.sh"
    echo "3. Monitor cache performance in your admin panel"
    echo "4. Configure CDN if needed"
    echo
    echo "Cache Management Commands:"
    echo "- Monitor cache: /usr/local/bin/mymeds-cache-monitor.sh"
    echo "- Backup cache: /usr/local/bin/mymeds-cache-backup.sh"
    echo "- Manual cache warming: sudo systemctl start mymeds-cache-warming.service"
    echo
    echo "Redis Management:"
    echo "- Start: sudo systemctl start redis-server"
    echo "- Stop: sudo systemctl stop redis-server"
    echo "- Status: sudo systemctl status redis-server"
    echo "- Logs: sudo journalctl -u redis-server"
}

# Run main function
main "$@"




