config:
  target: 'https://www.mymedspharmacyinc.com'
  phases:
    - duration: 60
      arrivalRate: 5
      name: "Warm up - 5 users per second"
    - duration: 120
      arrivalRate: 10
      name: "Ramp up - 10 users per second"
    - duration: 300
      arrivalRate: 20
      name: "Sustained load - 20 users per second"
    - duration: 120
      arrivalRate: 50
      name: "Peak load - 50 users per second"
    - duration: 60
      arrivalRate: 5
      name: "Cool down - 5 users per second"
  
  defaults:
    headers:
      User-Agent: 'Artillery Load Test'
      Accept: 'application/json, text/html, */*'
      Accept-Language: 'en-US,en;q=0.9'
      Accept-Encoding: 'gzip, deflate, br'
      Connection: 'keep-alive'
      Cache-Control: 'no-cache'
    
  plugins:
    metrics-by-endpoint: {}
    expect: {}
    
  processor: './load-tests/processors.js'
  
  environments:
    staging:
      target: 'https://staging.mymedspharmacyinc.com'
      phases:
        - duration: 30
          arrivalRate: 2
          name: "Staging test - 2 users per second"
    
    production:
      target: 'https://www.mymedspharmacyinc.com'
      phases:
        - duration: 60
          arrivalRate: 5
          name: "Warm up - 5 users per second"
        - duration: 120
          arrivalRate: 10
          name: "Ramp up - 10 users per second"
        - duration: 300
          arrivalRate: 20
          name: "Sustained load - 20 users per second"
        - duration: 120
          arrivalRate: 50
          name: "Peak load - 50 users per second"
        - duration: 60
          arrivalRate: 5
          name: "Cool down - 5 users per second"

scenarios:
  # Homepage and public pages
  - name: "Public Pages"
    weight: 40
    flow:
      - get:
          url: "/"
          expect:
            - statusCode: 200
            - contentType: html
      - think: 2
      - get:
          url: "/about"
          expect:
            - statusCode: 200
      - think: 1
      - get:
          url: "/services"
          expect:
            - statusCode: 200
      - think: 1
      - get:
          url: "/contact"
          expect:
            - statusCode: 200

  # Shop browsing
  - name: "Shop Browsing"
    weight: 30
    flow:
      - get:
          url: "/shop"
          expect:
            - statusCode: 200
      - think: 2
      - get:
          url: "/api/products"
          expect:
            - statusCode: 200
            - contentType: json
      - think: 1
      - get:
          url: "/product/1"
          expect:
            - statusCode: 200
      - think: 2
      - get:
          url: "/api/products/1"
          expect:
            - statusCode: 200

  # User authentication
  - name: "User Authentication"
    weight: 20
    flow:
      - get:
          url: "/admin-signin"
          expect:
            - statusCode: 200
      - think: 1
      - post:
          url: "/api/auth/login"
          json:
            email: "{{ $randomString() }}@test.com"
            password: "testpassword123"
          expect:
            - statusCode: [401, 400]
      - think: 1
      - get:
          url: "/admin"
          expect:
            - statusCode: [200, 401, 302]

  # API endpoints
  - name: "API Health Checks"
    weight: 10
    flow:
      - get:
          url: "/api/health"
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: "status"
      - think: 1
      - get:
          url: "/api/health/db"
          expect:
            - statusCode: 200
            - contentType: json





