config:
  target: 'https://mymedspharmacyinc.com'
  phases:
    - duration: 60
      arrivalRate: 5
      name: "Warm up"
    - duration: 120
      arrivalRate: 10
      name: "Ramp up load"
    - duration: 300
      arrivalRate: 20
      name: "Sustained load"
    - duration: 60
      arrivalRate: 5
      name: "Ramp down"
  environments:
    production:
      target: 'https://mymedspharmacyinc.com'
    staging:
      target: 'https://staging.mymedspharmacyinc.com'
    local:
      target: 'http://localhost:3000'
  plugins:
    metrics-by-endpoint: {}
  defaults:
    headers:
      User-Agent: "Artillery Load Test"
      Accept: "application/json, text/html, */*"

scenarios:
  - name: "Homepage Load Test"
    weight: 30
    flow:
      - get:
          url: "/"
          expect:
            - statusCode: 200
      - get:
          url: "/api/health"
          expect:
            - statusCode: 200

  - name: "Product Catalog Test"
    weight: 25
    flow:
      - get:
          url: "/shop"
          expect:
            - statusCode: 200
      - get:
          url: "/api/products"
          expect:
            - statusCode: 200

  - name: "Services Page Test"
    weight: 20
    flow:
      - get:
          url: "/services"
          expect:
            - statusCode: 200
      - get:
          url: "/about"
          expect:
            - statusCode: 200

  - name: "Contact Form Test"
    weight: 15
    flow:
      - get:
          url: "/contact"
          expect:
            - statusCode: 200
      - post:
          url: "/api/contact"
          json:
            name: "Load Test User"
            email: "test@example.com"
            message: "This is a load test message"
          expect:
            - statusCode: [200, 201]

  - name: "Admin Panel Test"
    weight: 10
    flow:
      - get:
          url: "/admin"
          expect:
            - statusCode: 200
      - get:
          url: "/admin/signin"
          expect:
            - statusCode: 200
